# Generated by Django 5.1.3 on 2024-11-17 19:58

import photogallery.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photogallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to=photogallery.models.user_directory_path),
        ),
    ]
