# Generated by Django 5.0.4 on 2024-11-21 17:45

import photogallery.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photogallery", "0002_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                storage=photogallery.models.MyS3BotoStorage,
                upload_to=photogallery.models.user_directory_path,
            ),
        ),
    ]
